before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: orsz52Cszs8V2qiQt75QY74YRcYeEUcElHCzv+g1ARlpQ2fCmhFnkVHM2iNzv6weN2IwR+iqIlnGqw+Xn4i9MpClACKGekA2YBZgTPhkID57D8vQXXLHJyiyHVkU7nMbn2x6owdKXXtRJT3nkdfVbIDmvfBAs4dJ8X+I52SJiEkRb4Rf8YR+ov/c8AO0IIrW+DPXuIKGEgwAAHmMv8JKeXcMhUU9m9n2pDaY4FvCwXaREAgt94rIlAN2Trqk43KnGuD5VygkqA+B2a8xLSXyeFAN3nxFI7cqTF9UdZz3syyoLK1gOhm9VdAzUxegrpcEY6klTmwlccMZqF2Fn+1DDqwRIjh/mP6iR73mBBFzYvGBOuUjSA4C7uiDg+jBCLgF3OCtk6EFr29t+PWPYCeNYQ00DF2b0LG3mcVWjjLnNrsxrnnrlZawYan41HvYG7y/SjVKBJkYsds1f963inC1o6NpVMafq7ZdknRJmedjh8RISJmnQqZeyGs+3g2lQvN7lxyORkRZbyXx3w0P2qXSepgbli1+Rc/pKAwzf5tRHlMraOis4vsqi0y+nzWBm/5sq1NqwxkHUMy52OLCejPykeQS5VNzweyz8YgvuWeahgAbi3BoukEiIhEA9EPrdTwMKatu3EwoTnZ3vuK4aQxiaPNLY5dYmIBtgFnTmm7EPCY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
